pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "JDK17"
    }
    
    environment {
        cluster = "vproappprod"
        service = "vproapptask-service-prod"
    }

    stages {
        stage('Deploy TO Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-2') {
                  sh """
                    aws ecs update-service \
                    --cluster ${cluster} \
                    --service ${service} \
                    --force-new-deployment
                  """
               }
           }
        }
             
    }

    post {
        always {
          echo 'Slack Notification'
          slackSend channel: '#',
          color: 
        }
    }
    
    // Optional: Post-Build-Actions....
    post {
        always {
            echo 'Pipeline abgeschlossen - Ergebnis: ${currentBuild.result}'
        }
        success {
            echo 'Pipeline war erfolgreich!'
        }
        failure {
            echo 'Pipeline ist fehlgeschlagen!'
        }
    }
}